/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project0;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Phonebook classUnderTest = new Phonebook();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
